### ISSUE TITLE
Cannot locate file

### ISSUE THREAD

**Issue by acdn-jbalasubramanian** [kpfaulkner/sendgrid-plugin#3]
lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=kpfaulkner-sendgrid-plugin error="fork/exec /var/lib/grafana/plugins/sendgrid-plugin/src/gpx_sendgrid-plugin_linux_amd64: no such file or directory"

I cannot find this anywhere and grafana complains about it during startup

**Comment by kpfaulkner** [comment]
Hi

Just to confirm, you've performed the following:

1) unzipped to a directory
2) modified the 2 entries in defaults.ini (and "plugins" and "allow_loading_unsigned_plugins" sections)
3) performed a chmod +x on the gpx_sendgrid-plugin_linux_amd64 file?

Thanks

Ken

**Comment by acdn-jbalasubramanian** [comment]
Thanks Ken, 

1. Extrarcted: yes
2. allow_loading_unsigned_plugins = kpfaulkner-sendgrid-plugin ( I tried a couple of variations)
3. find / -name gpx_sendgrid-plugin_linux_amd64.. I cannot find this file on the host.  

I can see the sendgrid in the GUI on grafana, just never loads.

**Comment by kpfaulkner** [comment]
![image](https://user-images.githubusercontent.com/116306/123527746-4d905b00-d725-11eb-9c34-61abd0f7d117.png)

In the zip file you should definitely see gpx_sendgrid-plugin_linux_amd64 (as per screenshot). Can you confirm you are NOT seeing that file?

**Comment by acdn-jbalasubramanian** [comment]
Decided to go another route w/o sendgrid.  Thanks!
